version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest' 
  nginx:
    restart: always
    image: 'doss/my-multi-nginx'
    ports:
      - '3050:80'
    depends_on: 
      - client
  api:
    image: 'doss/my-multi-server'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres
      - redis
  client:
    image: 'doss/my-multi-client'
    depends_on:
      - postgres
      - redis
  worker:
    image: 'doss/my-multi-worker'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis